/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secure;
import java.util.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Raphael
 */
public class books extends javax.swing.JFrame {
        
        Statement st=null;
        ResultSet rs=null;
        PreparedStatement prs=null;
        Connection conn = MySqlconnect.dbConnection() ;
    /**
     * Creates new form books
     */
    public books() {
        initComponents();
        bookstable();
    }
    void bookstable(){ 
        try{
        st = conn.createStatement();
        
        String sql=("Select BOOKID,TITLE,AUTHOR,CATEGORY,ISBN,PUBLICATION_DATE,PUBLISHERID,QTY,PRICE From Books Order by Bookid Desc");
        rs=st.executeQuery(sql);
        ResultSetMetaData metadata= rs.getMetaData();
        
        int col = metadata.getColumnCount();
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        Vector rows=new Vector();
        Vector columns=new Vector();
        
        for(int i=1; i<= col; i++){
            columns.addElement(metadata.getColumnName(i));
        }
        model.setColumnIdentifiers(columns);
        
        
        while (rs.next()){
        rows =new Vector();
        for (int j=1; j<= col; j++){
        rows.addElement(rs.getString(j));
        } 
        model.addRow(rows);
        }
        jTable1.setModel(model);
    }
        catch (Exception ex){
            System.out.println("exception 2 ");
    }                          
    }                                        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txttitle = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtauth = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtpr1 = new javax.swing.JTextField();
        txtpr2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setTitle("BOOKS");
        setMaximumSize(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("BOOK DATABASE");

        jButton8.setText("Search By Book ID");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter Book ID");

        txtbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbidActionPerformed(evt);
            }
        });

        jButton9.setText("Search By Book Title");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter Book Title");

        txttitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttitleActionPerformed(evt);
            }
        });

        jButton10.setText("Search By Author Name");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enter Author Name");

        txtauth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtauthActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ανθρωπιστικές επιστήμες", "θετικές-τεχνολογικές επιστήμες", "λογοτεχνία-δοκίμια", "μαγειρική", "οικογένεια-σπίτι", "οικονομικά", "παιδικά βιβλία", "περιβάλλον", "πληροφορική", "ταξίδια - τουρισμός", "τέχνες", "σπορ - αθλητισμός", "εκπαιδευτικά", "χόμπι - ελεύθερος χρόνος", "ημερολόγια", "audio books" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Category");

        jButton5.setText("Search By Category");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Search By Price");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtpr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpr1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");

        jButton7.setText("Books With Not Enough Qty");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpr1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpr2))
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttitle)
                            .addComponent(txtauth, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtbid)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtauth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtpr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          
          addBook b=new addBook();
        
        
        
        b.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         int selectedOption = JOptionPane.showConfirmDialog(null, 
                                  "Do You Wanna Delete Selectet Row?", 
                                  "Choose", 
                                  JOptionPane.YES_NO_OPTION); 
if (selectedOption == JOptionPane.YES_OPTION) {
    int rowsel=jTable1.getSelectedRow();
    int bookid=Integer.valueOf(jTable1.getValueAt(rowsel,0).toString());
        String delete = ("Delete  From BOOKS Where BOOKID ='"+bookid+"'");
        conn=MySqlconnect.dbConnection();
        
        try{st=conn.createStatement();
            
            st.executeUpdate(delete);
            
} catch (Exception ex){
            JOptionPane.showMessageDialog(null,"That Book Dose Not Exist");
  
    }//GEN-LAST:event_jButton3ActionPerformed
    }}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);
        
        
        try{
        st = conn.createStatement();
        
        String sql=("Select BOOKID,TITLE,AUTHOR,CATEGORY,ISBN,PUBLICATION_DATE,PUBLISHERID,QTY,PRICE From Books Order by bookid Desc");
        rs=st.executeQuery(sql);
        ResultSetMetaData metadata= rs.getMetaData();
        
        int col = metadata.getColumnCount();
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        Vector rows=new Vector();
        Vector columns=new Vector();
        
        for(int i=1; i<= col; i++){
            columns.addElement(metadata.getColumnName(i));
        }
        model.setColumnIdentifiers(columns);
        
        
        while (rs.next()){
        rows =new Vector();
        for (int j=1; j<= col; j++){
        rows.addElement(rs.getString(j));
        } 
        model.addRow(rows);
        }
        jTable1.setModel(model);
    }
        catch (Exception ex){
            System.out.println("exception 2 ");
    }                          
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        editbook edit=new editbook();
        int rowsel=jTable1.getSelectedRow();
        
        
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        
        edit.lblid.setText(String.valueOf(jTable1.getValueAt(rowsel,0).toString()));
        edit.txttitle.setText(String.valueOf(jTable1.getValueAt(rowsel,1).toString()));
        edit.txta.setText(String.valueOf(jTable1.getValueAt(rowsel,2).toString()));
        edit.catedit.setSelectedItem(String.valueOf(jTable1.getValueAt(rowsel,3).toString()));
        edit.txtisbn.setText(String.valueOf(jTable1.getValueAt(rowsel,4).toString()));
        edit.txtdate.setText(String.valueOf(jTable1.getValueAt(rowsel,5).toString()));
        edit.pubid.setSelectedItem(String.valueOf(jTable1.getValueAt(rowsel,6).toString()));
        edit.txtqty.setText(String.valueOf(jTable1.getValueAt(rowsel,7).toString()));
        edit.txtprice.setText(String.valueOf(jTable1.getValueAt(rowsel,8).toString()));
        edit.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);
        modelcl.setColumnCount(0);
        int bid=Integer.valueOf(txtbid.getText());
        try{
            st = conn.createStatement();

            String sql=("SELECT BOOKID,TITLE,AUTHOR,CATEGORY,ISBN,PUBLICATION_DATE,PUBLISHERID,QTY,PRICE FROM Books where bookid='"+bid+"'");
            rs=st.executeQuery(sql);
            ResultSetMetaData metadata= rs.getMetaData();

            int col = metadata.getColumnCount();
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            Vector rows=new Vector();
            Vector columns=new Vector();

            for(int i=1; i<= col; i++){
                columns.addElement(metadata.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            while (rs.next()){
                rows =new Vector();
                for (int j=1; j<= col; j++){
                    rows.addElement(rs.getString(j));
                }
                model.addRow(rows);
            }
            jTable1.setModel(model);
        }
        catch (Exception ex){
            System.out.println("exception 2 ");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbidActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);
        modelcl.setColumnCount(0);
        String title=String.valueOf(txttitle.getText());
        try{
            st = conn.createStatement();

            String sql=("SELECT BOOKID,TITLE,AUTHOR,CATEGORY,ISBN,PUBLICATION_DATE,PUBLISHERID,QTY,PRICE FROM Books where Title='"+title+"'");
            rs=st.executeQuery(sql);
            ResultSetMetaData metadata= rs.getMetaData();

            int col = metadata.getColumnCount();
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            Vector rows=new Vector();
            Vector columns=new Vector();

            for(int i=1; i<= col; i++){
                columns.addElement(metadata.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            while (rs.next()){
                rows =new Vector();
                for (int j=1; j<= col; j++){
                    rows.addElement(rs.getString(j));
                }
                model.addRow(rows);
            }
            jTable1.setModel(model);
        }
        catch (Exception ex){
            System.out.println("exception 2 ");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txttitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttitleActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);
        modelcl.setColumnCount(0);
        String author=String.valueOf(txtauth.getText());
        try{
            st = conn.createStatement();

            String sql=("SELECT BOOKID,TITLE,AUTHOR,CATEGORY,ISBN,PUBLICATION_DATE,PUBLISHERID,QTY,PRICE FROM Books where author='"+author+"' Order By Title Desc");
            rs=st.executeQuery(sql);
            ResultSetMetaData metadata= rs.getMetaData();

            int col = metadata.getColumnCount();
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            Vector rows=new Vector();
            Vector columns=new Vector();

            for(int i=1; i<= col; i++){
                columns.addElement(metadata.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            while (rs.next()){
                rows =new Vector();
                for (int j=1; j<= col; j++){
                    rows.addElement(rs.getString(j));
                }
                model.addRow(rows);
            }
            jTable1.setModel(model);
        }
        catch (Exception ex){
            System.out.println("exception 2 ");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtauthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtauthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtauthActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void txtpr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpr1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String categ=(String)jComboBox2.getSelectedItem();
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);
        modelcl.setColumnCount(0);
        String name=String.valueOf(txttitle.getText());
        try{
            st = conn.createStatement();

            String sql=("SELECT BOOKID,TITLE,AUTHOR,CATEGORY,ISBN,PUBLICATION_DATE,PUBLISHERID,QTY,PRICE FROM Books where Category='"+categ+"' Order By Title Desc");
            rs=st.executeQuery(sql);
            ResultSetMetaData metadata= rs.getMetaData();

            int col = metadata.getColumnCount();
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            Vector rows=new Vector();
            Vector columns=new Vector();

            for(int i=1; i<= col; i++){
                columns.addElement(metadata.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            while (rs.next()){
                rows =new Vector();
                for (int j=1; j<= col; j++){
                    rows.addElement(rs.getString(j));
                }
                model.addRow(rows);
            }
            jTable1.setModel(model);
        }
        catch (Exception ex){
            System.out.println("exception 2 ");
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);
        modelcl.setColumnCount(0);
        int price1=Integer.valueOf(txtpr1.getText());
        int price2=Integer.valueOf(txtpr2.getText());
        try{
            st = conn.createStatement();

            String sql=("SELECT BOOKID,TITLE,AUTHOR,CATEGORY,ISBN,PUBLICATION_DATE,PUBLISHERID,QTY,PRICE FROM Books where price Between '"+price1+"' And '"+price2+"' Order By price Asc");
            rs=st.executeQuery(sql);
            ResultSetMetaData metadata= rs.getMetaData();

            int col = metadata.getColumnCount();
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            Vector rows=new Vector();
            Vector columns=new Vector();

            for(int i=1; i<= col; i++){
                columns.addElement(metadata.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            while (rs.next()){
                rows =new Vector();
                for (int j=1; j<= col; j++){
                    rows.addElement(rs.getString(j));
                }
                model.addRow(rows);
            }
            jTable1.setModel(model);
        }
        catch (Exception ex){
            System.out.println("exception 2 ");
        }
                               
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);
        modelcl.setColumnCount(0);
        try{
            st = conn.createStatement();

            String sql=("SELECT BOOKID,TITLE,AUTHOR,CATEGORY,ISBN,PUBLICATION_DATE,PUBLISHERID,QTY,PRICE FROM Books where qty<=10 ORDER BY Qty ASC");
            rs=st.executeQuery(sql);
            ResultSetMetaData metadata= rs.getMetaData();

            int col = metadata.getColumnCount();
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            Vector rows=new Vector();
            Vector columns=new Vector();

            for(int i=1; i<= col; i++){
                columns.addElement(metadata.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            while (rs.next()){
                rows =new Vector();
                for (int j=1; j<= col; j++){
                    rows.addElement(rs.getString(j));
                }
                model.addRow(rows);
            }
            jTable1.setModel(model);
        }
        catch (Exception ex){
            System.out.println("exception 2 ");
        }

                      
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtauth;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtpr1;
    private javax.swing.JTextField txtpr2;
    private javax.swing.JTextField txttitle;
    // End of variables declaration//GEN-END:variables
}
