/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secure;
import java.util.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Raphael
 */
public class Users extends javax.swing.JFrame {
        Statement st=null;
        ResultSet rs=null;
        PreparedStatement prs=null;
        Connection conn = MySqlconnect.dbConnection() ;
    /**
     * Creates new form Users
     */
    public Users() {
        initComponents();
    userstable();
    }
    void userstable(){ 
        try{
        st = conn.createStatement();
        
        String sql=("Select * From LOGIN Order BY Username Desc");
        rs=st.executeQuery(sql);
        ResultSetMetaData metadata= rs.getMetaData();
        
        int col = metadata.getColumnCount();
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        Vector rows=new Vector();
        Vector columns=new Vector();
        
        for(int i=1; i<= col; i++){
            columns.addElement(metadata.getColumnName(i));
        }
        model.setColumnIdentifiers(columns);
        
        
        while (rs.next()){
        rows =new Vector();
        for (int j=1; j<= col; j++){
        rows.addElement(rs.getString(j));
        } 
        model.addRow(rows);
        }
        jTable1.setModel(model);
    }
        catch (Exception ex){
            System.out.println("exception 2 ");
    }                          
    }                                        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setTitle("USERS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("USERS DATABASE");

        jButton8.setText("Search By Username");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter Username");

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });

        jButton5.setText("Last 10 Sing In");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        adduser b=new adduser();

        b.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        edituser edit=new edituser();
        int rowsel=jTable1.getSelectedRow();

        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();

        edit.txtuser.setText(String.valueOf(jTable1.getValueAt(rowsel,0).toString()));
        edit.txtpass1.setText(String.valueOf(jTable1.getValueAt(rowsel,1).toString()));
        edit.txtpass2.setText(String.valueOf(jTable1.getValueAt(rowsel,1).toString()));
        edit.txtname.setText(String.valueOf(jTable1.getValueAt(rowsel,2).toString()));
        edit.txtbday.setText(String.valueOf(jTable1.getValueAt(rowsel,3).toString()));
        edit.txtemail.setText(String.valueOf(jTable1.getValueAt(rowsel,4).toString()));
       
        edit.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int selectedOption = JOptionPane.showConfirmDialog(null,
            "Do You Wanna Delete Selectet Row?",
            "Choose",
            JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            int rowsel=jTable1.getSelectedRow();
            String user=String.valueOf(jTable1.getValueAt(rowsel,0).toString());
            String delete = ("Delete  From Login Where Username ='"+user+"'");
            conn=MySqlconnect.dbConnection();

            try{st=conn.createStatement();

                st.executeUpdate(delete);

            } catch (Exception ex){
                JOptionPane.showMessageDialog(null,"That User Dose Not Exist");

    }//GEN-LAST:event_jButton3ActionPerformed
        }}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);

        try{
            st = conn.createStatement();

            String sql=("Select * From login Order by username DESC");
            rs=st.executeQuery(sql);
            ResultSetMetaData metadata= rs.getMetaData();

            int col = metadata.getColumnCount();
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            Vector rows=new Vector();
            Vector columns=new Vector();

            for(int i=1; i<= col; i++){
                columns.addElement(metadata.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            while (rs.next()){
                rows =new Vector();
                for (int j=1; j<= col; j++){
                    rows.addElement(rs.getString(j));
                }
                model.addRow(rows);
            }
            jTable1.setModel(model);
        }
        catch (Exception ex){
            System.out.println("exception 2 ");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);
        modelcl.setColumnCount(0);
        String user=String.valueOf(txtuser.getText());
        try{
            st = conn.createStatement();

            String sql=("SELECT * FROM login where username='"+user+"'");
            rs=st.executeQuery(sql);
            ResultSetMetaData metadata= rs.getMetaData();

            int col = metadata.getColumnCount();
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            Vector rows=new Vector();
            Vector columns=new Vector();

            for(int i=1; i<= col; i++){
                columns.addElement(metadata.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            while (rs.next()){
                rows =new Vector();
                for (int j=1; j<= col; j++){
                    rows.addElement(rs.getString(j));
                }
                model.addRow(rows);
            }
            jTable1.setModel(model);
        }
        catch (Exception ex){
            System.out.println("exception 2 ");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcl = (DefaultTableModel) jTable1.getModel();
        modelcl.setRowCount(0);
        modelcl.setColumnCount(0);
        String user=String.valueOf(txtuser.getText());
        try{
            st = conn.createStatement();

            String sql=("SELECT * FROM(Select * From login Order By LAST_LOGIN Desc) Where rownum<=10 Order By LAST_LOGIN Desc");
            rs=st.executeQuery(sql);
            ResultSetMetaData metadata= rs.getMetaData();

            int col = metadata.getColumnCount();
            DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            Vector rows=new Vector();
            Vector columns=new Vector();

            for(int i=1; i<= col; i++){
                columns.addElement(metadata.getColumnName(i));
            }
            model.setColumnIdentifiers(columns);

            while (rs.next()){
                rows =new Vector();
                for (int j=1; j<= col; j++){
                    rows.addElement(rs.getString(j));
                }
                model.addRow(rows);
            }
            jTable1.setModel(model);
        }
        catch (Exception ex){
            System.out.println("exception 2 ");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
